/** Two-language strings for the panel, keyed by a flat dotted name. */

type Strings = Record<string, string>;

const en: Strings = {
  "nav.overview": "Overview",
  "card.title": "Heading",
  "card.title_hint": "Leave empty for “StateGuard”.",
  "card.hide_when_healthy": "Hide the card when nothing is wrong",
  "card.show_suppressed": "Also show held-back problems",
  "card.show_suppressed_hint": "Snoozed, acknowledged, or waiting out a grace period.",
  "card.max": "Most rows to show",
  "card.max_hint": "Empty means no limit.",
  "card.severities": "Only these severities",
  "card.watches": "Only these watches",
  "card.filter_hint": "Nothing selected means everything is shown.",
  "card.no_watches": "No watches configured yet.",
  "nav.watches": "Watches",
  "nav.severities": "Severities",
  "nav.channels": "Channels",
  "ch.add": "Add channel",
  "ch.empty": "No channels yet. Without one, problems only appear in Home Assistant itself.",
  "ch.kind": "Type",
  "ch.name": "Name",
  "ch.enabled": "Active",
  "ch.test": "Send test",
  "ch.test_ok": "Test message sent.",
  "ch.test_failed": "Failed: {error}",
  "ch.test_missing": "Please fill in “{field}” first.",
  "ch.templates": "Message text",
  "ch.title_template": "Subject / title",
  "ch.template": "Body",
  "ch.template_hint": "Jinja2, like in Home Assistant. Available: watch, severity, count, problems (name, entity_id, state, reason, device, integration, url). Leave empty for the built-in text.",
  "ch.confirm_delete": "Delete channel “{name}”?",
  "ch.secret_kept": "Stored — type to replace",
  "ch.used_by": "used by {count} severities",
  "ch.unused": "not assigned to any severity",
  "kind.ha_service": "Home Assistant service",
  "kind.ha_service_hint": "Uses a notification that Home Assistant already has: a mobile app, a configured Telegram bot, the SMTP integration, a script.",
  "kind.smtp": "E-mail (SMTP)",
  "kind.smtp_hint": "Sends mail directly through your own mail server, independent of Home Assistant.",
  "kind.telegram": "Telegram",
  "kind.telegram_hint": "Posts into a chat through your own bot token.",
  "kind.pushover": "Pushover",
  "kind.pushover_hint": "Push notification through the Pushover service.",
  "kind.ntfy": "ntfy",
  "kind.ntfy_hint": "Publishes to an ntfy topic, on ntfy.sh or your own server.",
  "field.service": "Service",
  "field.target": "Target",
  "field.data": "Additional data (JSON)",
  "field.host": "Server",
  "field.port": "Port",
  "field.encryption": "Encryption",
  "field.username": "User name",
  "field.password": "Password",
  "field.sender": "Sender address",
  "field.recipients": "Recipients",
  "field.token": "Token",
  "field.chat_id": "Chat ID",
  "field.user_key": "User key",
  "field.device": "Device",
  "field.priority": "Priority",
  "field.sound": "Sound",
  "field.server": "Server",
  "field.topic": "Topic",
  "field.tags": "Tags",
  "sev.channels": "Channels",
  "sev.escalation_channels": "Additional channels when escalating",
  "editor.channels": "Extra channels (on top of the severity)",
  "nav.settings": "Settings",
  "nav.history": "History",
  "hist.empty": "No incidents recorded yet.",
  "hist.all_watches": "All watches",
  "hist.all_severities": "All severities",
  "hist.range": "Period",
  "hist.days": "{count} days",
  "hist.open_only": "Only unresolved",
  "hist.ongoing": "ongoing",
  "hist.resolved_after": "resolved after {duration}",
  "hist.escalated": "escalated",
  "hist.total": "{count} incidents",
  "hist.more": "Load more",

  "overview.healthy": "Everything is fine",
  "overview.healthy_sub": "No active problems across {watched} monitored entities.",
  "overview.problems": "{count} active problem",
  "overview.problems_plural": "{count} active problems",
  "overview.watching": "{watched} entities in {watches} watches",
  "overview.paused": "Monitoring is paused",
  "overview.paused_sub": "No alerts are raised while the monitoring switch is off.",
  "overview.resume": "Resume monitoring",
  "overview.pause": "Pause monitoring",
  "overview.run_check": "Check now",
  "overview.no_watches": "No watches yet",
  "overview.no_watches_sub": "Start from a template — it takes about a minute.",
  "overview.grace": "Grace period after restart",
  "overview.grace_sub": "Right after a restart many entities are briefly unavailable, so nothing is reported yet. Remaining:",
  "overview.internet_down": "No internet connection",
  "overview.internet_sub": "While {entity} reports down, nothing is reported.",
  "overview.current": "Current problems",
  "overview.suppressed": "Held back",
  "overview.pending": "Waiting for grace period",

  "watches.add": "Add watch",
  "watches.from_template": "From template",
  "watches.empty": "No watches configured yet.",
  "watches.covers_one": "covers 1 entity",
  "watches.covers": "covers {count} entities",

  "reason.unavailable_state": "state is “{state}”",
  "reason.stale": "no report for {age} (limit {limit})",
  "reason.numeric_below": "{value} (below {limit})",
  "reason.numeric_above": "{value} (above {limit})",
  "reason.numeric_below_attribute": "{attribute}: {value} (below {limit})",
  "reason.numeric_above_attribute": "{attribute}: {value} (above {limit})",
  "reason.numeric_outside": "{value} (outside {lower}–{upper})",
  "reason.numeric_inside": "{value} (inside {lower}–{upper})",
  "reason.numeric_outside_attribute": "{attribute}: {value} (outside {lower}–{upper})",
  "reason.numeric_inside_attribute": "{attribute}: {value} (inside {lower}–{upper})",
  "reason.state_match": "state “{state}” is one of {list}",
  "reason.state_match_not": "state “{state}” is none of {list}",
  "reason.state_duration": "has been “{state}” for {age} (limit {limit})",
  "reason.entity_missing": "entity no longer exists",

  "template.availability.name": "Availability",
  "template.availability.description": "Alerts when a labelled entity becomes unavailable or unknown.",
  "template.battery_low.name": "Battery low",
  "template.battery_low.description": "Alerts below 25 %, clearing again above 40 %. Works with percentage battery sensors of any name, including Homematic's operating voltage level.",
  "template.no_data.name": "No data",
  "template.no_data.description": "Alerts when an entity has not reported for 24 hours. Measured against the last report, so devices that keep sending the same value do not trigger it.",
  "template.security_devices.name": "Security devices",
  "template.security_devices.description": "The same availability check at security severity: alerts immediately and ignores quiet hours.",
  "template.missing_entities.name": "Missing entities",
  "template.missing_entities.description": "Alerts when a watched entity disappears from Home Assistant.",

  "editor.restart_grace_global": "Use the global grace period after a restart",

  "watches.paused": "paused",
  "watches.show_entities": "Show the entities this covers",
  "watches.hide_entities": "Hide the list",
  "watches.entities_none": "This watch currently covers no entities.",
  "watches.entity_ok": "fine",
  "watches.loading": "Loading…",
  "watches.edit": "Edit",
  "watches.delete": "Delete",
  "watches.confirm_delete": "Delete watch “{name}”?",

  "editor.new": "New watch",
  "editor.name": "Name",
  "editor.severity": "Severity",
  "editor.enabled": "Enabled",
  "editor.target": "What to watch",
  "editor.labels": "Labels",
  "editor.label_mode": "Label matching",
  "editor.label_mode_any": "Any of them",
  "editor.label_mode_all": "All of them",
  "editor.areas": "Areas",
  "editor.floors": "Floors",
  "editor.domains": "Domains",
  "editor.integrations": "Integrations",
  "editor.entities": "Individual entities",
  "editor.exclude_labels": "Exclude labels",
  "editor.exclude_entities": "Exclude entities",
  "editor.include_device_entities": "Include entities of labelled devices",
  "editor.include_diagnostic": "Include diagnostic and configuration entities",
  "editor.conditions": "What counts as a problem",
  "editor.add_condition": "Add condition",
  "editor.condition_or": "Each condition triggers on its own.",
  "editor.advanced": "Advanced",
  "editor.grace_period": "Wait before alerting",
  "editor.restart_grace": "Grace period after restart (empty = global)",
  "editor.overlap_mode": "If several watches cover an entity",
  "editor.overlap_all": "All of them alert",
  "editor.overlap_highest": "Only the highest severity",
  "editor.notify_on_clear": "Notify when resolved",
  "editor.suppress_by_parent": "Suppress when the parent device is down",
  "editor.group_alerts": "Bundle into one message",
  "editor.preview": "Currently covered",
  "editor.preview_none": "This selection covers no entities.",
  "editor.preview_count": "{count} entities",
  "editor.save": "Save",
  "editor.cancel": "Cancel",
  "editor.no_conditions": "Add at least one condition.",
  "editor.needs_name": "Give the watch a name.",

  "cond.unavailable_state": "Unavailable or unknown",
  "cond.stale": "No data for too long",
  "cond.numeric_threshold": "Numeric threshold",
  "cond.state_match": "State is (not)",
  "cond.state_duration": "Stuck in a state",
  "cond.entity_missing": "Entity disappeared",
  "cond.states": "States that count as a problem",
  "cond.time_basis": "Measure against",
  "cond.basis_last_reported": "Last report (recommended)",
  "cond.basis_last_updated": "Last update",
  "cond.basis_last_changed": "Last change",
  "cond.duration": "After",
  "cond.source": "Read from",
  "cond.source_state": "State",
  "cond.source_attribute": "Attribute…",
  "cond.operator": "Comparison",
  "cond.op_lt": "below",
  "cond.op_le": "at or below",
  "cond.op_gt": "above",
  "cond.op_ge": "at or above",
  "cond.op_outside": "outside a range",
  "cond.op_inside": "inside a range",
  "cond.state_empty": "(empty)",
  "cond.value": "Limit",
  "cond.value2": "Upper limit",
  "cond.recovery_value": "Clears again at",
  "cond.recovery_hint": "Leave empty to clear at the same limit.",
  "cond.target_state": "State",
  "cond.negate": "Invert (alert when it is NOT one of these)",
  "cond.remove": "Remove",

  "sev.add": "Add severity",
  "sev.name": "Name",
  "sev.priority": "Priority",
  "sev.priority_hint": "Higher wins when watches overlap.",
  "sev.color": "Colour",
  "color.primary": "Primary",
  "color.accent": "Accent",
  "color.red": "Red",
  "color.pink": "Pink",
  "color.purple": "Purple",
  "color.deep-purple": "Deep purple",
  "color.indigo": "Indigo",
  "color.blue": "Blue",
  "color.light-blue": "Light blue",
  "color.cyan": "Cyan",
  "color.teal": "Teal",
  "color.green": "Green",
  "color.light-green": "Light green",
  "color.lime": "Lime",
  "color.yellow": "Yellow",
  "color.amber": "Amber",
  "color.orange": "Orange",
  "color.deep-orange": "Deep orange",
  "color.brown": "Brown",
  "color.grey": "Grey",
  "color.blue-grey": "Blue grey",
  "color.black": "Black",
  "color.white": "White",
  "sev.icon": "Icon",
  "sev.ignore_quiet_hours": "Ignore quiet hours",
  "sev.persistent_notification": "Create a notification in Home Assistant",
  "sev.bundle_window": "Bundle for",
  "sev.bundle_hint": "0 = send immediately.",
  "sev.repeat_interval": "Repeat every",
  "sev.repeat_hint": "0 = do not repeat.",
  "sev.escalation_after": "Escalate after",
  "sev.escalation_hint": "0 = never escalate. Counted from the first alert.",
  "sev.in_use_one": "used by 1 watch",
  "sev.in_use": "used by {count} watches",
  "sev.confirm_delete": "Delete severity “{name}”?",

  "settings.monitoring": "Monitoring active",
  "settings.restart_grace": "Grace period after a Home Assistant restart",
  "settings.restart_hint": "Right after a restart many entities are briefly unavailable.",
  "settings.internet_entity": "Connectivity entity",
  "settings.internet_hint": "While this entity is off, nothing is reported. Leave empty to disable.",
  "settings.failed_integrations": "Report failed integrations",
  "settings.scope_watched": "Only integrations with watched entities",
  "settings.scope_all": "All integrations",
  "settings.quiet_hours": "Quiet hours",
  "settings.quiet_enabled": "Hold back alerts at night",
  "settings.quiet_from": "From",
  "settings.quiet_to": "To",
  "settings.quiet_hint": "Held back alerts are sent afterwards if the problem still stands.",
  "settings.add_window": "Add another period",
  "settings.remove_window": "Remove",
  "settings.window_wraps": "runs into the next day",
  "settings.no_windows": "No periods yet — nothing is held back.",
  "settings.window_no_days": "Pick at least one day, or this period does nothing.",
  "settings.weekdays": "Days",
  "settings.history_retention": "Keep history for",
  "settings.panel_access": "Who sees StateGuard in the sidebar",
  "settings.panel_admin": "Administrators only",
  "settings.panel_all": "Everyone (read-only for non-administrators)",
  "settings.panel_hint": "Changing anything always stays with administrators. The Lovelace card works for everyone regardless of this setting.",
  "overview.read_only": "You are seeing the status only. Changes are made by an administrator.",
  "settings.language": "Panel language",
  "settings.language_auto": "Follow Home Assistant",
  "settings.save": "Save settings",
  "settings.saved": "Saved",

  "unit.seconds": "seconds",
  "unit.minutes": "minutes",
  "unit.hours": "hours",
  "unit.days": "days",
  "link.entity": "Show entity",
  "link.device": "Go to device",
  "link.integration": "Go to integration",
  "common.none": "None",
  "common.search": "Search…",
  "common.close": "Close",
  "common.error": "Something went wrong: {message}",
  "error.not_loaded": "StateGuard is not set up.",
  "error.not_found": "This entry no longer exists.",
  "error.in_use": "Still used by: {names}",
  "day.0": "Mon",
  "day.1": "Tue",
  "day.2": "Wed",
  "day.3": "Thu",
  "day.4": "Fri",
  "day.5": "Sat",
  "day.6": "Sun",

  "sup.monitoring_off": "monitoring off",
  "sup.watch_disabled": "watch paused",
  "sup.snoozed": "snoozed",
  "sup.acknowledged": "acknowledged",
  "sup.restart_grace": "restart grace period",
  "sup.internet_down": "no internet",
  "sup.integration_down": "integration down",
  "sup.parent_down": "parent device down",
  "sup.quiet_hours": "quiet hours",
};

const de: Strings = {
  "nav.overview": "Übersicht",
  "card.title": "Überschrift",
  "card.title_hint": "Leer lassen für „StateGuard“.",
  "card.hide_when_healthy": "Karte ausblenden, wenn nichts ansteht",
  "card.show_suppressed": "Zurückgehaltene Probleme mit anzeigen",
  "card.show_suppressed_hint": "Geschlummert, quittiert oder in der Karenzzeit.",
  "card.max": "Höchstens so viele Zeilen",
  "card.max_hint": "Leer bedeutet unbegrenzt.",
  "card.severities": "Nur diese Schweregrade",
  "card.watches": "Nur diese Überwachungen",
  "card.filter_hint": "Nichts ausgewählt heißt: alles wird angezeigt.",
  "card.no_watches": "Noch keine Überwachungen eingerichtet.",
  "nav.watches": "Überwachungen",
  "nav.severities": "Schweregrade",
  "nav.channels": "Kanäle",
  "ch.add": "Kanal anlegen",
  "ch.empty": "Noch keine Kanäle. Ohne Kanal erscheinen Probleme nur in Home Assistant selbst.",
  "ch.kind": "Art",
  "ch.name": "Name",
  "ch.enabled": "Aktiv",
  "ch.test": "Test senden",
  "ch.test_ok": "Testnachricht verschickt.",
  "ch.test_failed": "Fehlgeschlagen: {error}",
  "ch.test_missing": "Bitte zuerst „{field}“ ausfüllen.",
  "ch.templates": "Nachrichtentext",
  "ch.title_template": "Betreff / Titel",
  "ch.template": "Inhalt",
  "ch.template_hint": "Jinja2, wie in Home Assistant. Verfügbar: watch, severity, count, problems (name, entity_id, state, reason, device, integration, url). Leer lassen für den eingebauten Text.",
  "ch.confirm_delete": "Kanal „{name}“ löschen?",
  "ch.secret_kept": "Gespeichert — zum Ersetzen neu eingeben",
  "ch.used_by": "von {count} Schweregraden genutzt",
  "ch.unused": "keinem Schweregrad zugeordnet",
  "kind.ha_service": "Home-Assistant-Dienst",
  "kind.ha_service_hint": "Nutzt eine Benachrichtigung, die Home Assistant schon hat: eine Handy-App, einen eingerichteten Telegram-Bot, die SMTP-Integration, ein Skript.",
  "kind.smtp": "E-Mail (SMTP)",
  "kind.smtp_hint": "Verschickt Mail direkt über deinen eigenen Mailserver, unabhängig von Home Assistant.",
  "kind.telegram": "Telegram",
  "kind.telegram_hint": "Schreibt über einen eigenen Bot-Token in einen Chat.",
  "kind.pushover": "Pushover",
  "kind.pushover_hint": "Push-Nachricht über den Dienst Pushover.",
  "kind.ntfy": "ntfy",
  "kind.ntfy_hint": "Veröffentlicht in einem ntfy-Topic, auf ntfy.sh oder deinem eigenen Server.",
  "field.service": "Dienst",
  "field.target": "Ziel",
  "field.data": "Zusätzliche Daten (JSON)",
  "field.host": "Server",
  "field.port": "Port",
  "field.encryption": "Verschlüsselung",
  "field.username": "Benutzername",
  "field.password": "Passwort",
  "field.sender": "Absenderadresse",
  "field.recipients": "Empfänger",
  "field.token": "Token",
  "field.chat_id": "Chat-ID",
  "field.user_key": "Benutzerschlüssel",
  "field.device": "Gerät",
  "field.priority": "Priorität",
  "field.sound": "Ton",
  "field.server": "Server",
  "field.topic": "Topic",
  "field.tags": "Tags",
  "sev.channels": "Kanäle",
  "sev.escalation_channels": "Zusätzliche Kanäle bei Eskalation",
  "editor.channels": "Zusätzliche Kanäle (zusätzlich zum Schweregrad)",
  "nav.settings": "Einstellungen",
  "nav.history": "Historie",
  "hist.empty": "Noch keine Vorfälle aufgezeichnet.",
  "hist.all_watches": "Alle Überwachungen",
  "hist.all_severities": "Alle Schweregrade",
  "hist.range": "Zeitraum",
  "hist.days": "{count} Tage",
  "hist.open_only": "Nur ungelöste",
  "hist.ongoing": "läuft noch",
  "hist.resolved_after": "behoben nach {duration}",
  "hist.escalated": "eskaliert",
  "hist.total": "{count} Vorfälle",
  "hist.more": "Mehr laden",

  "overview.healthy": "Alles in Ordnung",
  "overview.healthy_sub": "Keine aktiven Probleme bei {watched} überwachten Entitäten.",
  "overview.problems": "{count} aktives Problem",
  "overview.problems_plural": "{count} aktive Probleme",
  "overview.watching": "{watched} Entitäten in {watches} Überwachungen",
  "overview.paused": "Überwachung pausiert",
  "overview.paused_sub": "Solange der Schalter aus ist, wird nichts gemeldet.",
  "overview.resume": "Überwachung fortsetzen",
  "overview.pause": "Überwachung pausieren",
  "overview.run_check": "Jetzt prüfen",
  "overview.no_watches": "Noch keine Überwachungen",
  "overview.no_watches_sub": "Fang mit einer Vorlage an — dauert etwa eine Minute.",
  "overview.grace": "Karenzzeit nach Neustart",
  "overview.grace_sub": "Direkt nach einem Neustart sind viele Entitäten kurz nicht verfügbar, deshalb wird noch nichts gemeldet. Verbleibend:",
  "overview.internet_down": "Keine Internetverbindung",
  "overview.internet_sub": "Solange {entity} aus ist, wird nichts gemeldet.",
  "overview.current": "Aktuelle Probleme",
  "overview.suppressed": "Zurückgehalten",
  "overview.pending": "Wartet auf Karenzzeit",

  "watches.add": "Überwachung anlegen",
  "watches.from_template": "Aus Vorlage",
  "watches.empty": "Noch keine Überwachungen eingerichtet.",
  "watches.covers_one": "erfasst 1 Entität",
  "watches.covers": "erfasst {count} Entitäten",

  "reason.unavailable_state": "Zustand ist „{state}“",
  "reason.stale": "seit {age} keine Meldung (Grenze {limit})",
  "reason.numeric_below": "{value} (unter {limit})",
  "reason.numeric_above": "{value} (über {limit})",
  "reason.numeric_below_attribute": "{attribute}: {value} (unter {limit})",
  "reason.numeric_above_attribute": "{attribute}: {value} (über {limit})",
  "reason.numeric_outside": "{value} (außerhalb {lower}–{upper})",
  "reason.numeric_inside": "{value} (innerhalb {lower}–{upper})",
  "reason.numeric_outside_attribute": "{attribute}: {value} (außerhalb {lower}–{upper})",
  "reason.numeric_inside_attribute": "{attribute}: {value} (innerhalb {lower}–{upper})",
  "reason.state_match": "Zustand „{state}“ ist einer von {list}",
  "reason.state_match_not": "Zustand „{state}“ ist keiner von {list}",
  "reason.state_duration": "seit {age} „{state}“ (Grenze {limit})",
  "reason.entity_missing": "Entität existiert nicht mehr",

  "template.availability.name": "Verfügbarkeit",
  "template.availability.description": "Meldet, wenn eine gelabelte Entität nicht mehr verfügbar oder unbekannt ist.",
  "template.battery_low.name": "Batterie schwach",
  "template.battery_low.description": "Meldet ab 25 % und entwarnt wieder über 40 %. Funktioniert mit prozentualen Batteriesensoren jeder Benennung, auch mit dem Betriebsspannungspegel von Homematic.",
  "template.no_data.name": "Keine Daten",
  "template.no_data.description": "Meldet, wenn eine Entität 24 Stunden lang nichts gemeldet hat. Gemessen an der letzten Meldung, damit Geräte mit gleichbleibendem Wert nicht auslösen.",
  "template.security_devices.name": "Sicherheitsgeräte",
  "template.security_devices.description": "Dieselbe Verfügbarkeitsprüfung mit Schweregrad Sicherheit: meldet sofort und ignoriert Ruhezeiten.",
  "template.missing_entities.name": "Verschwundene Entitäten",
  "template.missing_entities.description": "Meldet, wenn eine überwachte Entität aus Home Assistant verschwindet.",

  "editor.restart_grace_global": "Globale Karenzzeit nach Neustart verwenden",

  "watches.paused": "pausiert",
  "watches.show_entities": "Erfasste Entitäten anzeigen",
  "watches.hide_entities": "Liste ausblenden",
  "watches.entities_none": "Diese Überwachung erfasst derzeit keine Entitäten.",
  "watches.entity_ok": "in Ordnung",
  "watches.loading": "Wird geladen…",
  "watches.edit": "Bearbeiten",
  "watches.delete": "Löschen",
  "watches.confirm_delete": "Überwachung „{name}“ löschen?",

  "editor.new": "Neue Überwachung",
  "editor.name": "Name",
  "editor.severity": "Schweregrad",
  "editor.enabled": "Aktiv",
  "editor.target": "Was überwacht wird",
  "editor.labels": "Labels",
  "editor.label_mode": "Label-Verknüpfung",
  "editor.label_mode_any": "Eines davon",
  "editor.label_mode_all": "Alle davon",
  "editor.areas": "Bereiche",
  "editor.floors": "Etagen",
  "editor.domains": "Domains",
  "editor.integrations": "Integrationen",
  "editor.entities": "Einzelne Entitäten",
  "editor.exclude_labels": "Labels ausschließen",
  "editor.exclude_entities": "Entitäten ausschließen",
  "editor.include_device_entities": "Entitäten gelabelter Geräte einbeziehen",
  "editor.include_diagnostic": "Diagnose- und Konfigurationsentitäten einbeziehen",
  "editor.conditions": "Was als Problem gilt",
  "editor.add_condition": "Bedingung hinzufügen",
  "editor.condition_or": "Jede Bedingung löst für sich aus.",
  "editor.advanced": "Erweitert",
  "editor.grace_period": "Warten vor der Meldung",
  "editor.restart_grace": "Karenzzeit nach Neustart (leer = global)",
  "editor.overlap_mode": "Wenn mehrere Überwachungen dieselbe Entität erfassen",
  "editor.overlap_all": "Alle melden",
  "editor.overlap_highest": "Nur der höchste Schweregrad",
  "editor.notify_on_clear": "Entwarnung senden",
  "editor.suppress_by_parent": "Unterdrücken, wenn das Elterngerät ausgefallen ist",
  "editor.group_alerts": "Zu einer Nachricht bündeln",
  "editor.preview": "Aktuell erfasst",
  "editor.preview_none": "Diese Auswahl erfasst keine Entitäten.",
  "editor.preview_count": "{count} Entitäten",
  "editor.save": "Speichern",
  "editor.cancel": "Abbrechen",
  "editor.no_conditions": "Mindestens eine Bedingung hinzufügen.",
  "editor.needs_name": "Bitte einen Namen vergeben.",

  "cond.unavailable_state": "Nicht verfügbar oder unbekannt",
  "cond.stale": "Zu lange keine Daten",
  "cond.numeric_threshold": "Zahlenwert-Schwelle",
  "cond.state_match": "Zustand ist (nicht)",
  "cond.state_duration": "Hängt in einem Zustand",
  "cond.entity_missing": "Entität verschwunden",
  "cond.states": "Zustände, die als Problem gelten",
  "cond.time_basis": "Gemessen an",
  "cond.basis_last_reported": "Letzter Meldung (empfohlen)",
  "cond.basis_last_updated": "Letzter Aktualisierung",
  "cond.basis_last_changed": "Letzter Wertänderung",
  "cond.duration": "Nach",
  "cond.source": "Gelesen aus",
  "cond.source_state": "Zustand",
  "cond.source_attribute": "Attribut…",
  "cond.operator": "Vergleich",
  "cond.op_lt": "unter",
  "cond.op_le": "kleiner oder gleich",
  "cond.op_gt": "über",
  "cond.op_ge": "größer oder gleich",
  "cond.op_outside": "außerhalb eines Bereichs",
  "cond.op_inside": "innerhalb eines Bereichs",
  "cond.state_empty": "(leer)",
  "cond.value": "Grenzwert",
  "cond.value2": "Obergrenze",
  "cond.recovery_value": "Entwarnung ab",
  "cond.recovery_hint": "Leer lassen, um beim selben Grenzwert zu entwarnen.",
  "cond.target_state": "Zustand",
  "cond.negate": "Umkehren (melden, wenn NICHT einer davon)",
  "cond.remove": "Entfernen",

  "sev.add": "Schweregrad anlegen",
  "sev.name": "Name",
  "sev.priority": "Priorität",
  "sev.priority_hint": "Der höhere gewinnt bei Überschneidungen.",
  "sev.color": "Farbe",
  "color.primary": "Primär",
  "color.accent": "Akzent",
  "color.red": "Rot",
  "color.pink": "Pink",
  "color.purple": "Violett",
  "color.deep-purple": "Dunkelviolett",
  "color.indigo": "Indigo",
  "color.blue": "Blau",
  "color.light-blue": "Hellblau",
  "color.cyan": "Türkis",
  "color.teal": "Petrol",
  "color.green": "Grün",
  "color.light-green": "Hellgrün",
  "color.lime": "Limette",
  "color.yellow": "Gelb",
  "color.amber": "Bernstein",
  "color.orange": "Orange",
  "color.deep-orange": "Dunkelorange",
  "color.brown": "Braun",
  "color.grey": "Grau",
  "color.blue-grey": "Blaugrau",
  "color.black": "Schwarz",
  "color.white": "Weiß",
  "sev.icon": "Symbol",
  "sev.ignore_quiet_hours": "Ruhezeiten ignorieren",
  "sev.persistent_notification": "Benachrichtigung in Home Assistant anlegen",
  "sev.bundle_window": "Bündeln für",
  "sev.bundle_hint": "0 = sofort senden.",
  "sev.repeat_interval": "Wiederholen alle",
  "sev.repeat_hint": "0 = nicht wiederholen.",
  "sev.escalation_after": "Eskalieren nach",
  "sev.escalation_hint": "0 = keine Eskalation. Gerechnet ab der Erstmeldung.",
  "sev.in_use_one": "von 1 Überwachung genutzt",
  "sev.in_use": "von {count} Überwachungen genutzt",
  "sev.confirm_delete": "Schweregrad „{name}“ löschen?",

  "settings.monitoring": "Überwachung aktiv",
  "settings.restart_grace": "Karenzzeit nach einem Neustart von Home Assistant",
  "settings.restart_hint": "Direkt nach einem Neustart sind viele Entitäten kurz nicht verfügbar.",
  "settings.internet_entity": "Entität für die Internetverbindung",
  "settings.internet_hint": "Solange diese Entität aus ist, wird nichts gemeldet. Leer lassen zum Abschalten.",
  "settings.failed_integrations": "Ausgefallene Integrationen melden",
  "settings.scope_watched": "Nur Integrationen mit überwachten Entitäten",
  "settings.scope_all": "Alle Integrationen",
  "settings.quiet_hours": "Ruhezeiten",
  "settings.quiet_enabled": "Meldungen nachts zurückhalten",
  "settings.quiet_from": "Von",
  "settings.quiet_to": "Bis",
  "settings.quiet_hint": "Zurückgehaltene Meldungen kommen danach, wenn das Problem noch besteht.",
  "settings.add_window": "Weiteren Zeitraum hinzufügen",
  "settings.remove_window": "Entfernen",
  "settings.window_wraps": "geht in den nächsten Tag",
  "settings.no_windows": "Noch keine Zeiträume — es wird nichts zurückgehalten.",
  "settings.window_no_days": "Mindestens einen Tag wählen, sonst greift der Zeitraum nie.",
  "settings.weekdays": "Tage",
  "settings.history_retention": "Historie aufbewahren",
  "settings.panel_access": "Wer StateGuard in der Seitenleiste sieht",
  "settings.panel_admin": "Nur Administratoren",
  "settings.panel_all": "Alle (für Nicht-Administratoren nur lesend)",
  "settings.panel_hint": "Ändern dürfen immer nur Administratoren. Die Lovelace-Karte funktioniert unabhängig von dieser Einstellung für alle.",
  "overview.read_only": "Du siehst nur den Status. Änderungen nimmt ein Administrator vor.",
  "settings.language": "Sprache des Panels",
  "settings.language_auto": "Wie Home Assistant",
  "settings.save": "Einstellungen speichern",
  "settings.saved": "Gespeichert",

  "unit.seconds": "Sekunden",
  "unit.minutes": "Minuten",
  "unit.hours": "Stunden",
  "unit.days": "Tage",
  "link.entity": "Entität anzeigen",
  "link.device": "Zum Gerät",
  "link.integration": "Zur Integration",
  "common.none": "Keine",
  "common.search": "Suchen…",
  "common.close": "Schließen",
  "common.error": "Da ist etwas schiefgegangen: {message}",
  "error.not_loaded": "StateGuard ist nicht eingerichtet.",
  "error.not_found": "Dieser Eintrag existiert nicht mehr.",
  "error.in_use": "Wird noch verwendet von: {names}",
  "day.0": "Mo",
  "day.1": "Di",
  "day.2": "Mi",
  "day.3": "Do",
  "day.4": "Fr",
  "day.5": "Sa",
  "day.6": "So",

  "sup.monitoring_off": "Überwachung aus",
  "sup.watch_disabled": "Überwachung pausiert",
  "sup.snoozed": "schlummert",
  "sup.acknowledged": "quittiert",
  "sup.restart_grace": "Karenzzeit nach Neustart",
  "sup.internet_down": "kein Internet",
  "sup.integration_down": "Integration ausgefallen",
  "sup.parent_down": "Elterngerät ausgefallen",
  "sup.quiet_hours": "Ruhezeit",
};

const catalogues: Record<string, Strings> = { en, de };

/** Build a translator for the given language, falling back to English. */
export function localize(language: string): (key: string, vars?: Record<string, string | number>) => string {
  const short = (language || "en").split("-")[0];
  const table = catalogues[short] ?? en;
  return (key, vars) => {
    let text = table[key] ?? en[key] ?? key;
    if (vars) {
      for (const [name, value] of Object.entries(vars)) {
        text = text.replace(new RegExp(`\\{${name}\\}`, "g"), String(value));
      }
    }
    return text;
  };
}

export type Localizer = ReturnType<typeof localize>;
